# -*- coding: utf-8 -*-
"""Environment Setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T10Lqz0bPgMPmGY9N2ohxxudKyAacGRn
"""

!pip install gymnasium

!pip install swig
!pip install gymnasium[box2d]

import gymnasium as gym
import Box2D

env=gym.make('LunarLanderContinuous-v2',render_mode='human')

env.action_space#what is a Box Class?

env.reset()

action=env.action_space.sample()

infoTuple=env.step(action)
infoTuple#(observation,reward,terminated,truncated,information)

